feat(src/extension/_locales/en): better messages
adobe/helix-sidekick-extension pull request #178
Opened 2022-11-14 16:59 UTC by MarquiseRosier

make error messages, more clearly show what users must do to make Sidekick work when invalid url error is given

## Related Issues
#169 

Thanks for contributing!

2022-11-19 09:34 UTC, rofe requested changes
@kptdobe could you give the French translation a look?

2022-11-19 09:34 UTC, rofe commented on src/extension/_locales/de/messages.json
> +    "message": "Ungültige Repository-URL, muss beginnen mit https://github.com"
I think I would change this to 
```suggestion
    "message": "Ungültige Repository-URL, muss mit https://github.com beginnen"
```

2022-11-21 09:24 UTC, kptdobe commented on src/extension/_locales/fr/messages.json
> +    "message": "URL de référentiel non valide, doit commencer par https://github.com"
I would simplify the message to: 
```suggestion
    "message": "L'URL du projet doit commencer par https://github.com"
```

2023-02-07 19:37 UTC, rofe commented
@MarquiseRosier are you going to finish this PR?

2023-05-30 12:12 UTC, rofe commented
Closing due to inactivity.

2023-05-30 12:12 UTC, closed without merging