Better error messages for Word Docs and Excel Sheets
adobe/helix-sidekick-extension pull request #203
Opened 2022-12-14 18:17 UTC by ahmed-musallam

Detect when the user attempts to publish a Microsoft Doc or Microsoft Excel Sheet and display appropriate messages to convert them; MS Doc and MS Excel sheets are not supported by helix.

Please ensure your pull request adheres to the following guidelines:
- [ ] make sure to link the related issues in this description
- [ ] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues

Thanks for contributing!

2022-12-14 18:19 UTC, ahmed-musallam commented on src/extension/de.css
> +  content: "Previewing failed. This is a Microsoft Doc. Please convert it to a Google Doc: 'File' > 'Save As Google Doc'";
Need help translating this.

2022-12-17 15:03 UTC, rofe requested changes

2022-12-17 15:03 UTC, rofe commented on src/extension/fr.css
> +}
Adjusted to proposed English text. @kptdobe could you provide the French translation?
```suggestion
.hlx-sk-overlay .modal.modal-preview-not-gdoc-ms-doc::before {
  content: "This is a Microsoft Word document. Please convert it to a Google Doc: File > Save as Google Docs";
}

.hlx-sk-overlay .modal.modal-preview-not-gsheet-ms-excel::before {
  content: "This is a Microsoft Excel document. Please convert it to Google Sheets: File > Save as Google Sheets";
}
```

2022-12-20 08:36 UTC, kptdobe requested changes
Provided french translations

2022-12-20 08:36 UTC, kptdobe commented on src/extension/fr.css
> +  content: "This is a Microsoft Word document. Please convert it to a Google Doc: File > Save as Google Docs";
```suggestion
  content: "Ce document est un fichier Microsoft Word, vous devez le convertir en document Google Doc: Fichier > Enregistrer comme Google Docs";
```

2022-12-20 08:36 UTC, kptdobe commented on src/extension/fr.css
> +  content: "This is a Microsoft Excel document. Please convert it to Google Sheets: File > Save as Google Sheets";
```suggestion
  content: "Ce document est un fichier Microsoft Excel, vous devez le convertir en document Google Sheets: Fichier > Enregistrer comme Google Sheets";
```

2022-12-20 19:32 UTC, rofe requested changes

2022-12-20 19:32 UTC, rofe commented on src/extension/de.css
> +  content: "Dies ist ein Microsoft Word-Dokument. Bitte in Google-Tabelle umwandeln: Datei > Als Google-Tabelle speichern";
Wrong product 😬 
```suggestion
  content: "Dies ist ein Microsoft Excel-Dokument. Bitte in Google-Tabelle umwandeln: Datei > Als Google-Tabelle speichern";
```

2022-12-21 08:12 UTC, kptdobe approved these changes

2022-12-22 15:25 UTC, rofe approved these changes

2022-12-22 15:25 UTC, merged

2022-12-29 22:46 UTC, tripodsan commented
:tada: This PR is included in version 6.6.1 :tada:

The release is available on:
- [GitHub release](https://github.com/adobe/helix-sidekick-extension/releases/tag/v6.6.1)
- `v6.6.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: