fix: don't set credentials:include when in devMode
adobe/helix-sidekick-extension pull request #349
Opened 2023-05-10 14:18 UTC by dylandepass

Fixes #348 

Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

## Related Issues
#348 

Thanks for contributing!

2023-05-10 15:08 UTC, dylandepass commented
Thanks for taking a look @tripodsan 

Yes I see what you mean. What's weird is I did test this and I was able to preview using the sidekick when in devMode with this change. Let me dig deeper and see what that was.

Alternatively, maybe we can just omit  `credentials=include` just to requests to `tools/sidekick/config.json` when in devMode.

2023-05-10 16:34 UTC, tripodsan commented on src/extension/module.js
> +      credentials: devMode ? 'omit' : 'include',
I would tweak the `opts` below, when fetching the config

2023-05-10 19:18 UTC, rofe requested changes

2023-05-10 19:18 UTC, rofe commented on src/extension/module.js
> +  function getAdminFetchOptions(config, omitCredentials = false) {
Probably a leftover from a previous version. Let’s remove it.

2023-05-11 05:33 UTC, tripodsan approved these changes

2023-05-11 07:48 UTC, rofe approved these changes

2023-05-11 07:49 UTC, merged

2023-05-11 08:17 UTC, trieloff commented
:tada: This PR is included in version 6.15.1 :tada:

The release is available on:
- [GitHub release](https://github.com/adobe/helix-sidekick-extension/releases/tag/v6.15.1)
- `v6.15.1`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: