chore(test): export c8 coverage from puppeteer
adobe/helix-sidekick-extension pull request #466
Opened 2023-08-02 13:40 UTC by dominique-pfister

exports script coverage from puppeteer to c8 in a compatible format

2023-08-02 14:43 UTC, dominique-pfister commented on web-test-runner.config.cjs
> +    include: ['./src/**'],
just cover `src` tree

2023-08-02 20:59 UTC, rofe requested changes

2023-08-02 20:59 UTC, rofe commented on .nycrc.json
>    "branches": 100,
Let's lower branch coverage to 81.5 for now
```suggestion
  "branches": 81.5,
```

2023-08-03 08:40 UTC, rofe approved these changes

2023-08-03 08:40 UTC, merged

2023-08-04 09:10 UTC, trieloff commented
:tada: This PR is included in version 6.26.0 :tada:

The release is available on:
- [GitHub release](https://github.com/adobe/helix-sidekick-extension/releases/tag/v6.26.0)
- `v6.26.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: