fix: initiator domains
adobe/helix-sidekick-extension pull request #782
Opened 2024-08-15 15:23 UTC by rofe

Limit initiator domains that can make authentictaed admin API requests.

2024-08-15 17:36 UTC, tripodsan approved these changes

2024-08-15 18:02 UTC, tripodsan requested changes
hi. we also need to include the custom preview and live hosts.

2024-08-16 10:24 UTC, rofe commented
> hi. we also need to include the custom preview and live hosts.

They are included. But the mountpoint hostname is still missing, therefore the sidekick is getting a 401 in edit mode.

2024-08-19 21:24 UTC, rofe commented
Abandoning this approach since it can never work for all configured and transient sites within an org.

2024-08-19 21:24 UTC, closed without merging