Issue 806
adobe/helix-sidekick-extension pull request #807
Opened 2024-09-16 13:06 UTC by rofe

Fix #806

2024-09-16 18:27 UTC, tripodsan requested changes
LGTM, but we want to allow uppercase foldernames....(to be tested)

2024-09-16 21:04 UTC, rofe commented on src/extension/module.js
> +          if (safePath !== status.webPath) {
@tripodsan I purposely left the case as is here, because coming from the webPath, it should already be lowercased, no?

2024-09-18 07:07 UTC, rofe commented
As discussed, sidekick is relying on `edit.illegalPath` now for the folder path validity.

2024-09-18 07:13 UTC, tripodsan approved these changes

2024-09-19 08:20 UTC, rofe commented on src/extension/module.js
> +      if (type === 'xlsx' || (type === 'spreadsheet' && ext !== '.xlsx')) {
Unrelated to the current issue, but was causing a generic error if someone previewed an excel file from gdrive. Now a user-friendly error message gets displayed.

2024-09-19 14:55 UTC, tripodsan approved these changes

2024-09-24 08:23 UTC, merged

2024-09-24 18:45 UTC, trieloff commented
:tada: This PR is included in version 6.49.2 :tada:

The release is available on:
- [GitHub release](https://github.com/adobe/helix-sidekick-extension/releases/tag/v6.49.2)
- `v6.49.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: