Translations Update, please integrate
adobe/helix-sidekick-extension pull request #846
Opened 2024-10-29 02:50 UTC by rgeraghty

please merge. cc @rgeraght

2024-10-29 08:02 UTC, rofe requested changes
@rgeraghty I'd like to keep the gender of the sidekick (male) as is since people are already used to it and changing it now may be confusing.

Also, this PR accidentally reverts the localized chrome web store URLs.

2024-10-29 15:56 UTC, rgeraghty commented
@rofe the URL's are corrected, for the mascaline change, is that for German?
![Screenshot 2024-10-29 at 8 55 17 AM](https://github.com/user-attachments/assets/b52d97dd-0e5d-43c9-90da-f7057972fd0e)

2024-11-08 07:02 UTC, rofe requested changes

2024-11-08 07:02 UTC, rofe commented on src/extension/_locales/de/messages.json
> +    "message": "Den neuen AEM Sidekick schließen"
```suggestion
    "message": "Den neuen AEM Sidekick installieren"
```

2024-11-13 15:30 UTC, rgeraghty commented on src/extension/_locales/de/messages.json
> +    "message": "Den neuen AEM Sidekick schließen"
@rofe translation has been updated,

2024-11-13 16:38 UTC, rofe approved these changes

2024-11-13 16:39 UTC, merged